/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bsb_hike_voip_SpeexDSPWrapper */

#ifndef _Included_com_bsb_hike_voip_SpeexDSPWrapper
#define _Included_com_bsb_hike_voip_SpeexDSPWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bsb_hike_voip_SpeexDSPWrapper
 * Method:    resampler_create
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_bsb_hike_voip_SpeexDSPWrapper_resampler_1create
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_bsb_hike_voip_SpeexDSPWrapper
 * Method:    resampler_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bsb_hike_voip_SpeexDSPWrapper_resampler_1destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
