/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bsb_hike_voip_SolicallWrapper */

#ifndef _Included_com_bsb_hike_voip_SolicallWrapper
#define _Included_com_bsb_hike_voip_SolicallWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bsb_hike_voip_SolicallWrapper
 * Method:    packageInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bsb_hike_voip_SolicallWrapper_packageInit
  (JNIEnv *, jobject);

/*
 * Class:     com_bsb_hike_voip_SolicallWrapper
 * Method:    AECInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bsb_hike_voip_SolicallWrapper_AECInit
  (JNIEnv *, jobject, jint, jint, jshort, jshort, jshort, jint);

/*
 * Class:     com_bsb_hike_voip_SolicallWrapper
 * Method:    processSpeakerFrame
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_bsb_hike_voip_SolicallWrapper_processSpeakerFrame
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_bsb_hike_voip_SolicallWrapper
 * Method:    processMicFrame
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_bsb_hike_voip_SolicallWrapper_processMicFrame
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_bsb_hike_voip_SolicallWrapper
 * Method:    terminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bsb_hike_voip_SolicallWrapper_terminate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
