// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataPacket.proto

package com.bsb.hike.voip.protobuf;

public final class DataPacketProtoBuf {
  private DataPacketProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DataPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataPacket)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required bool encrypted = 1;</code>
     */
    boolean hasEncrypted();
    /**
     * <code>required bool encrypted = 1;</code>
     */
    boolean getEncrypted();

    /**
     * <code>optional bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional string destinationIP = 3;</code>
     */
    boolean hasDestinationIP();
    /**
     * <code>optional string destinationIP = 3;</code>
     */
    java.lang.String getDestinationIP();
    /**
     * <code>optional string destinationIP = 3;</code>
     */
    com.google.protobuf.ByteString
        getDestinationIPBytes();

    /**
     * <code>optional int32 destinationPort = 4;</code>
     */
    boolean hasDestinationPort();
    /**
     * <code>optional int32 destinationPort = 4;</code>
     */
    int getDestinationPort();

    /**
     * <code>required int32 packetType = 5;</code>
     */
    boolean hasPacketType();
    /**
     * <code>required int32 packetType = 5;</code>
     */
    int getPacketType();

    /**
     * <code>optional int32 packetNumber = 6;</code>
     */
    boolean hasPacketNumber();
    /**
     * <code>optional int32 packetNumber = 6;</code>
     */
    int getPacketNumber();

    /**
     * <code>optional bool requiresAck = 7;</code>
     */
    boolean hasRequiresAck();
    /**
     * <code>optional bool requiresAck = 7;</code>
     */
    boolean getRequiresAck();

    /**
     * <code>optional int32 voicePacketNumber = 8;</code>
     */
    boolean hasVoicePacketNumber();
    /**
     * <code>optional int32 voicePacketNumber = 8;</code>
     */
    int getVoicePacketNumber();

    /**
     * <code>optional int64 timestamp = 9;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 9;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code DataPacket}
   */
  public static final class DataPacket extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:DataPacket)
      DataPacketOrBuilder {
    // Use DataPacket.newBuilder() to construct.
    private DataPacket(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataPacket(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final DataPacket defaultInstance;
    public static DataPacket getDefaultInstance() {
      return defaultInstance;
    }

    public DataPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private DataPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              encrypted_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destinationIP_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              destinationPort_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              packetType_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              packetNumber_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              requiresAck_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              voicePacketNumber_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<DataPacket> PARSER =
        new com.google.protobuf.AbstractParser<DataPacket>() {
      public DataPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENCRYPTED_FIELD_NUMBER = 1;
    private boolean encrypted_;
    /**
     * <code>required bool encrypted = 1;</code>
     */
    public boolean hasEncrypted() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool encrypted = 1;</code>
     */
    public boolean getEncrypted() {
      return encrypted_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int DESTINATIONIP_FIELD_NUMBER = 3;
    private java.lang.Object destinationIP_;
    /**
     * <code>optional string destinationIP = 3;</code>
     */
    public boolean hasDestinationIP() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string destinationIP = 3;</code>
     */
    public java.lang.String getDestinationIP() {
      java.lang.Object ref = destinationIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destinationIP_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destinationIP = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationIPBytes() {
      java.lang.Object ref = destinationIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATIONPORT_FIELD_NUMBER = 4;
    private int destinationPort_;
    /**
     * <code>optional int32 destinationPort = 4;</code>
     */
    public boolean hasDestinationPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 destinationPort = 4;</code>
     */
    public int getDestinationPort() {
      return destinationPort_;
    }

    public static final int PACKETTYPE_FIELD_NUMBER = 5;
    private int packetType_;
    /**
     * <code>required int32 packetType = 5;</code>
     */
    public boolean hasPacketType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 packetType = 5;</code>
     */
    public int getPacketType() {
      return packetType_;
    }

    public static final int PACKETNUMBER_FIELD_NUMBER = 6;
    private int packetNumber_;
    /**
     * <code>optional int32 packetNumber = 6;</code>
     */
    public boolean hasPacketNumber() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 packetNumber = 6;</code>
     */
    public int getPacketNumber() {
      return packetNumber_;
    }

    public static final int REQUIRESACK_FIELD_NUMBER = 7;
    private boolean requiresAck_;
    /**
     * <code>optional bool requiresAck = 7;</code>
     */
    public boolean hasRequiresAck() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool requiresAck = 7;</code>
     */
    public boolean getRequiresAck() {
      return requiresAck_;
    }

    public static final int VOICEPACKETNUMBER_FIELD_NUMBER = 8;
    private int voicePacketNumber_;
    /**
     * <code>optional int32 voicePacketNumber = 8;</code>
     */
    public boolean hasVoicePacketNumber() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 voicePacketNumber = 8;</code>
     */
    public int getVoicePacketNumber() {
      return voicePacketNumber_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 9;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 timestamp = 9;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      encrypted_ = false;
      data_ = com.google.protobuf.ByteString.EMPTY;
      destinationIP_ = "";
      destinationPort_ = 0;
      packetType_ = 0;
      packetNumber_ = 0;
      requiresAck_ = false;
      voicePacketNumber_ = 0;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEncrypted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPacketType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, encrypted_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDestinationIPBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, destinationPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, packetType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, packetNumber_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, requiresAck_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, voicePacketNumber_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, timestamp_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, encrypted_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDestinationIPBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, destinationPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, packetType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, packetNumber_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, requiresAck_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, voicePacketNumber_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timestamp_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code DataPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:DataPacket)
        com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacketOrBuilder {
      // Construct using com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        encrypted_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        destinationIP_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        destinationPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        packetType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        packetNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        requiresAck_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        voicePacketNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket getDefaultInstanceForType() {
        return com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket.getDefaultInstance();
      }

      public com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket build() {
        com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket buildPartial() {
        com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket result = new com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.encrypted_ = encrypted_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destinationIP_ = destinationIP_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.destinationPort_ = destinationPort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packetType_ = packetType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.packetNumber_ = packetNumber_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.requiresAck_ = requiresAck_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.voicePacketNumber_ = voicePacketNumber_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket other) {
        if (other == com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket.getDefaultInstance()) return this;
        if (other.hasEncrypted()) {
          setEncrypted(other.getEncrypted());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasDestinationIP()) {
          bitField0_ |= 0x00000004;
          destinationIP_ = other.destinationIP_;
          
        }
        if (other.hasDestinationPort()) {
          setDestinationPort(other.getDestinationPort());
        }
        if (other.hasPacketType()) {
          setPacketType(other.getPacketType());
        }
        if (other.hasPacketNumber()) {
          setPacketNumber(other.getPacketNumber());
        }
        if (other.hasRequiresAck()) {
          setRequiresAck(other.getRequiresAck());
        }
        if (other.hasVoicePacketNumber()) {
          setVoicePacketNumber(other.getVoicePacketNumber());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEncrypted()) {
          
          return false;
        }
        if (!hasPacketType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bsb.hike.voip.protobuf.DataPacketProtoBuf.DataPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean encrypted_ ;
      /**
       * <code>required bool encrypted = 1;</code>
       */
      public boolean hasEncrypted() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool encrypted = 1;</code>
       */
      public boolean getEncrypted() {
        return encrypted_;
      }
      /**
       * <code>required bool encrypted = 1;</code>
       */
      public Builder setEncrypted(boolean value) {
        bitField0_ |= 0x00000001;
        encrypted_ = value;
        
        return this;
      }
      /**
       * <code>required bool encrypted = 1;</code>
       */
      public Builder clearEncrypted() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encrypted_ = false;
        
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        
        return this;
      }

      private java.lang.Object destinationIP_ = "";
      /**
       * <code>optional string destinationIP = 3;</code>
       */
      public boolean hasDestinationIP() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string destinationIP = 3;</code>
       */
      public java.lang.String getDestinationIP() {
        java.lang.Object ref = destinationIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destinationIP_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destinationIP = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationIPBytes() {
        java.lang.Object ref = destinationIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinationIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destinationIP = 3;</code>
       */
      public Builder setDestinationIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destinationIP_ = value;
        
        return this;
      }
      /**
       * <code>optional string destinationIP = 3;</code>
       */
      public Builder clearDestinationIP() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destinationIP_ = getDefaultInstance().getDestinationIP();
        
        return this;
      }
      /**
       * <code>optional string destinationIP = 3;</code>
       */
      public Builder setDestinationIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destinationIP_ = value;
        
        return this;
      }

      private int destinationPort_ ;
      /**
       * <code>optional int32 destinationPort = 4;</code>
       */
      public boolean hasDestinationPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 destinationPort = 4;</code>
       */
      public int getDestinationPort() {
        return destinationPort_;
      }
      /**
       * <code>optional int32 destinationPort = 4;</code>
       */
      public Builder setDestinationPort(int value) {
        bitField0_ |= 0x00000008;
        destinationPort_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 destinationPort = 4;</code>
       */
      public Builder clearDestinationPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        destinationPort_ = 0;
        
        return this;
      }

      private int packetType_ ;
      /**
       * <code>required int32 packetType = 5;</code>
       */
      public boolean hasPacketType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 packetType = 5;</code>
       */
      public int getPacketType() {
        return packetType_;
      }
      /**
       * <code>required int32 packetType = 5;</code>
       */
      public Builder setPacketType(int value) {
        bitField0_ |= 0x00000010;
        packetType_ = value;
        
        return this;
      }
      /**
       * <code>required int32 packetType = 5;</code>
       */
      public Builder clearPacketType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packetType_ = 0;
        
        return this;
      }

      private int packetNumber_ ;
      /**
       * <code>optional int32 packetNumber = 6;</code>
       */
      public boolean hasPacketNumber() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 packetNumber = 6;</code>
       */
      public int getPacketNumber() {
        return packetNumber_;
      }
      /**
       * <code>optional int32 packetNumber = 6;</code>
       */
      public Builder setPacketNumber(int value) {
        bitField0_ |= 0x00000020;
        packetNumber_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 packetNumber = 6;</code>
       */
      public Builder clearPacketNumber() {
        bitField0_ = (bitField0_ & ~0x00000020);
        packetNumber_ = 0;
        
        return this;
      }

      private boolean requiresAck_ ;
      /**
       * <code>optional bool requiresAck = 7;</code>
       */
      public boolean hasRequiresAck() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool requiresAck = 7;</code>
       */
      public boolean getRequiresAck() {
        return requiresAck_;
      }
      /**
       * <code>optional bool requiresAck = 7;</code>
       */
      public Builder setRequiresAck(boolean value) {
        bitField0_ |= 0x00000040;
        requiresAck_ = value;
        
        return this;
      }
      /**
       * <code>optional bool requiresAck = 7;</code>
       */
      public Builder clearRequiresAck() {
        bitField0_ = (bitField0_ & ~0x00000040);
        requiresAck_ = false;
        
        return this;
      }

      private int voicePacketNumber_ ;
      /**
       * <code>optional int32 voicePacketNumber = 8;</code>
       */
      public boolean hasVoicePacketNumber() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 voicePacketNumber = 8;</code>
       */
      public int getVoicePacketNumber() {
        return voicePacketNumber_;
      }
      /**
       * <code>optional int32 voicePacketNumber = 8;</code>
       */
      public Builder setVoicePacketNumber(int value) {
        bitField0_ |= 0x00000080;
        voicePacketNumber_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 voicePacketNumber = 8;</code>
       */
      public Builder clearVoicePacketNumber() {
        bitField0_ = (bitField0_ & ~0x00000080);
        voicePacketNumber_ = 0;
        
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 9;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 timestamp = 9;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 9;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000100;
        timestamp_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 timestamp = 9;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timestamp_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DataPacket)
    }

    static {
      defaultInstance = new DataPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DataPacket)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
